---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/10/8 21:57
---

local downloaded_from_cdn = {}
local function replace_url(origin)
    -- 只从 cdn 下载一次，如果再次下载，直接从 cos 上下载
    if downloaded_from_cdn[origin] then return origin end
    -- 这几行下载地址的替换的代码（从cos地址变换成cdn地址）每个环境都不一样
    local cos = '%-maps%-1257933509%.cos%.ap%-shanghai%.myqcloud%.com'
    local cdn = '-maps-1257933509.file.myqcloud.com'

    local new_url = origin:gsub(cos, cdn, 1, true)

    log.info('cdn url after replace: ' .. new_url)
    downloaded_from_cdn[origin] = new_url
    return new_url
end

local replace_local_url = function(origin)
    local origin_prefix = ''
    local replaced = ''
    if _G.IP:find('172.27.105.') == nil and _G.IP ~= '127.0.0.1' and _G.IP ~= 'e.alpha.sce.xd.com' then
        return
    end
    --if _G.IP:find('172.27.105.') or _G.IP == '127.0.0.1' then

    if _G.IP == 'e.inner-alpha.sce.xd.com' then
        origin_prefix = 'alpha%-maps%-1257933509%.cos%.ap%-shanghai%.myqcloud%.com'
        replaced = 'mir.alpha.sce.xd.com'
    else
        origin_prefix = 'inner%-maps%-1257933509%.cos%.ap%-shanghai%.myqcloud%.com'
        replaced = 'up.master.sce.xd.com'
    end
    --else
    --    origin_prefix = 'new%-engine%-maps%-formal%-1257933509%.cos%.ap%-shanghai%.myqcloud%.com'
    --end

    --if packet_type == 3 then
    --    -- local new_url1 = origin:gsub(origin_prefix, 'up2.master.sce.xd.com')  -- 172.27.105.110
    --    local new_url2 = origin:gsub(origin_prefix, 'up.master.sce.xd.com')  -- 172.27.105.2
    --    return new_url2
    --else
        local new_url1 = origin:gsub(origin_prefix, replaced)  -- 172.27.105.2
        -- local new_url2 = origin:gsub(origin_prefix, 'up2.master.sce.xd.com')  -- 172.27.105.110
        return new_url1
    --end
end

local ali_replace_url = function(origin)
    local cos = 'sce%-maps%-(%g+)%.oss%-(%g+)%.aliyuncs'
    local cdn = 'package-%1.spark.xd' 

    local new_url = origin:gsub(cos, cdn)
    if not new_url or new_url == origin then
        local cos2 = 'sce%-maps%-(%w+)%.oss%-accelerate%.aliyuncs'
        new_url = origin:gsub(cos2, cdn)
    end

    if base.new_base_domain then
        new_url = new_url:gsub('spark%.xd%.com', base.new_base_domain)
    end

    return new_url
end

local terrain_replace_url = function(origin)
    local cos = 'random%-terrain%-(%g+)%.oss%-(%g+)%.aliyuncs.com'
    local cdn = 'random-terrain-static-%1.spark.xd.com'

    local new_url = origin:gsub(cos, cdn)
    return new_url
end

return {
    ali_replace_url,
    replace_local_url,
    terrain_replace_url
}