---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XINDONG.
--- DateTime: 2022/6/28 16:01
---


env_test_dict.get_client_id_token = function()
    coroutine.sleep(6000)
    local http = sce.httplib.create()
    local output = sce.httplib.create_stream()

    local key_version = 1 -- 暂时固定
    local noise = 'asdjaldsjjllkj'  -- 要随机!
    local map_name = 'aaa1_ng7a'
    local unixtime = tostring(os.time())  -- UTC unix timestamp

    local url = fmt('http://e.master.sce.xd.com:9006/api/client-token/v1/query?map_name=%s&time=%s&noise=%s&key_version=%s', map_name, unixtime, noise, key_version)
    local code, status = coroutine.call(sce.httplib.request, {
        url = url,
        method = 'GET',
        output = output,
    })

    if code == 0 and status == 200 then
        local out_str = output:read()
        log_file.info(('http_with_login_token1 success. body: %s'):format(out_str))

        local j = json.decode(out_str)
        local client_token = j.client_token  -- 这是个number[]
        local client_id = j.client_id        -- 同上
        local server_noise = j.server_noise  -- 服务器的随机字符串

        common.set_client_id_token(client_id, 0, noise, unixtime, server_noise, map_name)     -- 通知client_id给c++
        common.set_client_id_token(client_token, 1, noise, unixtime, server_noise, map_name)  -- 通知client_token给c++
    else
        assert(code == 0 and status == 200, fmt('http_with_login_token1 failed. code[%s], status[%s]', code, status))
    end
end
