---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/2/25 10:44
---

require 'base.exception'


env_test_dict.exception_example1 = function()
    local err  ---@type Exception

    xpcall(function()
        error '123'
    end, function(err1)
        xpcall(function()
            err = to_exception(err1)
        end, log.error)
    end)

    assert(err ~= nil)
    assert(instance_of(err, Exception))

    xpcall(function()
        assert(to_exception(err) == err)
        throw(err)
    end, function(err2)
        err = err2
    end)

    local err_str = tostring(err)
    assert(err_str:find('++++++++++\n.*+++++++++\n') ~= nil)
    log_file.info(err_str)
end
