---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuri.
--- DateTime: 2022/5/29 23:51
---

local account           = require 'base.account'

if __lua_state_name ~= 'StateGame' then
    env_test_dict.http_with_login_token1 = function()
        coroutine.sleep(6000)
        local http = sce.httplib.create()
        local output = sce.httplib.create_stream()
        local code, status = coroutine.call(account.http_request_with_token, http, {
            url = 'http://127.0.0.1:9006/api/simple-server/v1/test-token-checker',
            method = 'GET',
            output = output,
        })

        if code == 0 and status == 200 then
            log_file.info(('http_with_login_token1 success. body: %s'):format(output:read()))
        else
            assert(code == 0 and status == 200, fmt('http_with_login_token1 failed. code[%s], status[%s]', code, status))
        end
    end
end