---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/2/25 22:16
---

require 'base.co'


env_test_dict.http_example1 = function()
    local pro = base.promise()
    local outstream = sce.httplib.create_stream()
    sce.httplib.request ({
        url = 'http://www.baidu.com/',
        output = outstream,

    },function(code, status_code)
        if code == 0 and status_code == 200 then
            local buff = outstream:read()
            --log.error(buff)
            assert(#buff > 400)  -- 百度主页起码400字节吧

        else
            log.error(('http_example1 error[%s]'):format(code))
        end
    end)
end

env_test_dict.http_example2 = function()
    local outstream = sce.httplib.create_stream()
    local co_request = coroutine.co_wrap(sce.httplib.request)
    local code, status_code = co_request {
        url = 'http://www.baidu.com/',
        output = outstream,
    }

    if code == 0 and status_code == 200 then
        local buff = outstream:read()
        --log.error(buff)
        assert(buff > 200)  -- 百度主页起码200字节吧
    else
        log.error(('http_example1 error[%s]'):format(code))
        throw(('http_example1 error[%s]'):format(code))
    end
end
