---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by meiqi.
--- DateTime: 2024/1/22 21:16
---
local argv = require 'base.argv'

local function get_client_id()
	if argv.has('server') then
		local server_str = argv.get('server')
		if server_str == 'e.alpha.sce.xd.com' or server_str == 'editor-alpha.spark.xd.com' or server_str == 'e.fj-review.spark.xd.com' or server_str == 'editor-fj-review.spark.xd.com' then
			-- 测试服(alpha)
			return "qllpthuj3ep4aywb0o"
		elseif server_str == 'e.beta.sce.xd.com' or server_str == 'e.beta.spark.xd.com' or server_str == '172.20.67.14' or server_str == 'editor-beta.spark.xd.com' then
			-- 测试服(beta)
			return 'mntdx77vu0jk07fatr'
		elseif server_str == 'e.production.spark.xd.com' or server_str == 'e.formal.sce.xd.com' or server_str == 'e.formal.spark.xd.com' or server_str == 'editor-pd.spark.xd.com' then
			return 'YGySNSXKlgec6kROit'
		elseif server_str == 'e.intl.spark.xd.com' or server_str == 'e.intl-beta.spark.xd.com' or server_str == 'editor-intl.spark.xd.com' or server_str == 'editor-intl-beta.spark.xd.com' then --海外和海外准线上暂时用同一个clientid
			return 'yrhvhmeeevciti1cl5'
		end
	end
	if argv.has('rnd') then
		return 'l9drdpy3jbouxeysmg'
	end
	return '5csnnikv4bp68x6qxz'
end

_G.client_id = get_client_id()