---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/9/18 21:04
---

-- log_file挪到C++了，这里只是做个兼容
if not _G.log_file then
    _G.log_file = log
end

require 'main'
